### PR TITLE
Bugfixes for craftbukkit-1.4.6-R0.1

### PR DESCRIPTION
**Pull request by TimeSpawning**
Due to the new version of craftbukkit the class Packet103SetSlot is no longer available and breaks the method updateSlotInventory. But it seems like it became unnecessary as the inventory is updated automatically. Therefore I removed it completely. In addition to that the file plugin.yml has to be moved to the root directory in order to be read correctly by craftbukkit.

As I use eclipse several git-ignores were required.

### CODE REVIEW

**Comment by attrib** [comment]
I checked the code and checked why I added this function at the beginning.
The purpose of this method is that the items didn't get repaired when adding base items to the grid. So you add a damaged item to the grid and one base item. The item is then repaired to say 75% percent. After this add one base item (change the amount of base items in the grid). The repaired output slot is still changing, after removing this function?

Sorry I dont have mc installed at my laptop here, so i cant test it.

**Comment by TimeSpawning** [comment]
Okay I understand. As I've not done a full-blown test this is indeed something I have not tested yet. I'll do that later and report the result.

EDIT: Yes you are right the method is required, otherwise it does not update appropriately. My mistake.

**Comment by TimeSpawning** [comment]
After some research I found out:

For all plugins on BukkitDev access to CraftBukkit and/or Minecraft API is denied.
http://forums.bukkit.org/threads/safeguarding-against-unchecked-and-potentially-damaging-plugins.116749/

Therefore you can not use Packet103SetSlot to update the player's inventory (even if it actually does exist). I'll try to find a work around.

**Comment by attrib** [comment]
The Class Packet103 should still exists and we can still use this. We only have to check, how to use this class.

> "We are not trying to make utilising Minecraft or CraftBukkit code within your plugins more difficult, we are simply trying to promote using it more responsibly if you have a need to do so within your plugins."

**Comment by TimeSpawning** [comment]
But it also says:
"There are several ways to bypass this safeguard that I'm sure many of you
will be discussing on these forums, however, we would like to make it clear
that plugins using any bypass that includes dynamic code generation will be
denied from BukkitDev without hesitation due to the inherent security risks
it poses for servers."

**Comment by attrib** [comment]
We have to do more research here. But this will take a while and I think I won't get it done here at the conference.

**Comment by attrib** [comment]
Tried to fix this. Can you please test it? On my Laptop MC doesn't run. The server starts fine, with this.
http://dl.dropbox.com/u/26399435/RepairRecipe-beta2-v0.4.2.jar
See beta branch: https://github.com/attrib/RepairRecipe/tree/beta

It is allowed to use these functions, like I did. What is not allowed is not depending on versioned MC Packages. So this should be fine.

**Comment by TimeSpawning** [comment]
It still does not run on my server:
- Compile it with 1.6
- Move the plugin.yml to the root

Then it runs without errors and it does well :) I tested it, problems solved. Repair sound works, too. But you still have to change the two things above.

Another thing that caught my eye: When you repair an item with say 5 ingots, but you need only 2, there will be 4 ingots displayed in the workbench's grid until you drag the ingots. I then updates to 3. Is this a known issue or something which came up with these recent changes?

**Comment by attrib** [comment]
For the bug mentioned, can you please open a new ticket for this? Therefore I definitely need minecraft to check and fix this. So this will not be done before second January weekend.

> Move the plugin.yml to the root

This is something in your eclipse configuration. If I build the artifact, it copy the plugin.yml into the root folder of the jar (see the dropbox link)

> Compile it with 1.6

I'll do this now.
Update: I recompiled it with java6 and updated the uploaded file.

**Comment by attrib** [comment]
Big thanks again for your help!

**Pull request closed without merging**
